layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  google_scholar: https://scholar.google.com/citations?user=1TXnPsYAAAAJ&hl=en
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: zacharyl_cn
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 12912214
  # telegram: your_username
  twitter: Zachary__Lu
  # unsplash: your_username
  # vk: your_username
  
  # youtube: your_username
  website: http://roobooot.github.io

topics:
  - name: Professional
    web_url: /news/profession
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Google_Scholar_logo.svg/2048px-Google_Scholar_logo.svg.png
  - name: Personal
    web_url: /about
    image_url: https://bnz05pap001files.storage.live.com/y4mB0-KdEyWDioKfSw-YvVgxntmFjJKZvAN29qOfy89b20zCdhDAFENApyn1zC11zsEjbYGkufKDcWHnvtf-Di2TMVJOTDUpeauW_kBmxebLUfzxsRKUSa0gbZva38HEXMB1gxcPOZJ51GcwCE9i3hM8wvM7gK7_OIaQGL-kjIYGU95KC6xoY-EEDpDUowzT-ez?width=1024&height=576&cropmode=none


theme: jekyll-theme-tactile