layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  google_scholar: https://scholar.google.com/citations?user=1TXnPsYAAAAJ&hl=en
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: zacharyl_cn
  # keybase: your_username
  linkedin: zeyu-l-19b8241ba
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 12912214
  # telegram: your_username
  twitter: Zachary__Lu
  # unsplash: your_username
  # vk: your_username
  youtube: channel/UCK_TeWk6JFdWDFgm9uod50A
  website: http://roobooot.github.io

topics:
#  - name: Professional
#    web_url: /profession
#    image_url: https://mpng.subpng.com/20190107/pyb/kisspng-scalable-vector-graphics-computer-icons-clip-art-p-asap-tangampcompany-5c335dab209568.8136441115468701871335.jpg
#  - name: Photograph
#    web_url: /about
#    image_url: https://cdn-icons-png.flaticon.com/512/146/146031.png

# theme: jekyll-theme-tactile
theme: jekyll-theme-cayman
